# Generated by Django 5.2.7 on 2025-11-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_making', '0002_profile_making_is_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_making',
            name='profile_image',
            field=models.ImageField(default='default/user.png', upload_to='profile_images/'),
        ),
    ]
