# Generated by Django 5.2.7 on 2025-11-15 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Lost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('date_lost', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
