# Generated by Django 5.2.7 on 2025-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_lost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_lost',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default='2025-11-20'),
            preserve_default=False,
        ),
    ]
